// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using iptu.Data;

namespace iptu.Migrations
{
    [DbContext(typeof(iptuContext))]
    [Migration("20210219122348_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("iptu.Models.Dados", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Acordo");

                    b.Property<string>("AcordoAutoInfracao");

                    b.Property<int>("Ano");

                    b.Property<int>("Inclusao");

                    b.Property<string>("Inscrito");

                    b.Property<string>("Processando");

                    b.Property<string>("Processo");

                    b.HasKey("ID");

                    b.ToTable("Dados");
                });
#pragma warning restore 612, 618
        }
    }
}
